# Generated by Django 5.2.14 on 2026-05-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('auto_send', models.BooleanField(default=False)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords that trigger auto-reply. Leave empty to reply to all.')),
                ('custom_instructions', models.TextField(blank=True, help_text='Custom AI instructions for generating replies in this channel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_auto_rules', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
                ('thread_ts', models.CharField(blank=True, max_length=50)),
                ('ai_classification', models.CharField(blank=True, choices=[('question', 'Question'), ('request', 'Request'), ('fyi', 'FYI / Informational'), ('urgent', 'Urgent'), ('general', 'General')], max_length=20)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_reply', models.TextField(blank=True)),
                ('is_auto_replied', models.BooleanField(default=False)),
                ('reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_messages', to='companies.company')),
            ],
            options={
                'ordering': ['-tracked_at'],
                'unique_together': {('company', 'channel_id', 'timestamp')},
            },
        ),
    ]
