from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from companies.models import Company, Invitation, Membership, PlatformAccess, ActivityLog
from integrations.models import CompanyIntegration


class CompanyModelTests(TestCase):
    def test_slug_autogenerated(self):
        c = Company.objects.create(name="Acme Inc")
        self.assertEqual(c.slug, "acme-inc")

    def test_slug_is_unique(self):
        Company.objects.create(name="Acme Inc")
        c2 = Company.objects.create(name="Acme Inc")
        self.assertNotEqual(c2.slug, "acme-inc")
        self.assertTrue(c2.slug.startswith("acme-inc-"))

    def test_owner_property(self):
        user = User.objects.create_user("alice", password="pw")
        c = Company.objects.create(name="Acme")
        Membership.objects.create(user=user, company=c, role=Membership.Role.OWNER)
        self.assertEqual(c.owner, user)


class MembershipTests(TestCase):
    def test_unique_user_company(self):
        user = User.objects.create_user("alice", password="pw")
        c = Company.objects.create(name="Acme")
        Membership.objects.create(user=user, company=c, role=Membership.Role.OWNER)
        with self.assertRaises(Exception):
            Membership.objects.create(user=user, company=c, role=Membership.Role.MEMBER)

    def test_role_helpers(self):
        user = User.objects.create_user("alice", password="pw")
        c = Company.objects.create(name="Acme")
        m = Membership.objects.create(user=user, company=c, role=Membership.Role.OWNER)
        self.assertTrue(m.is_owner)
        self.assertTrue(m.is_admin)


class RegistrationFlowTests(TestCase):
    def test_registration_creates_company_and_owner_membership(self):
        url = reverse("accounts:register")
        response = self.client.post(url, {
            "company_name": "TestCo",
            "username": "bob",
            "first_name": "Bob",
            "last_name": "Builder",
            "email": "bob@test.co",
            "password1": "VeryStrongPass123!",
            "password2": "VeryStrongPass123!",
        })
        self.assertEqual(response.status_code, 302)
        user = User.objects.get(username="bob")
        company = Company.objects.get(name="TestCo")
        membership = Membership.objects.get(user=user, company=company)
        self.assertEqual(membership.role, Membership.Role.OWNER)

    def test_middleware_sets_company_on_request(self):
        user = User.objects.create_user("alice", password="VeryStrongPass123!")
        c = Company.objects.create(name="Acme")
        Membership.objects.create(user=user, company=c, role=Membership.Role.OWNER)
        self.client.login(username="alice", password="VeryStrongPass123!")
        response = self.client.get(reverse("accounts:profile"))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["current_company"], c)
        self.assertEqual(response.context["current_membership"].role, Membership.Role.OWNER)


# ── Phase 3 Tests ─────────────────────────────────────────────────────────────


class InvitationModelTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_user("admin", email="admin@co.com", password="pw")
        self.company = Company.objects.create(name="Acme")
        Membership.objects.create(user=self.admin, company=self.company, role=Membership.Role.OWNER)

    def test_create_invitation(self):
        inv = Invitation.objects.create(
            company=self.company,
            email="new@co.com",
            role=Membership.Role.MEMBER,
            invited_by=self.admin,
            expires_at=timezone.now() + timezone.timedelta(days=7),
        )
        self.assertEqual(inv.status, Invitation.Status.PENDING)
        self.assertTrue(inv.is_valid)
        self.assertFalse(inv.is_expired)

    def test_expired_invitation_is_invalid(self):
        inv = Invitation.objects.create(
            company=self.company,
            email="old@co.com",
            invited_by=self.admin,
            expires_at=timezone.now() - timezone.timedelta(hours=1),
        )
        self.assertTrue(inv.is_expired)
        self.assertFalse(inv.is_valid)

    def test_revoked_invitation_is_invalid(self):
        inv = Invitation.objects.create(
            company=self.company,
            email="rev@co.com",
            invited_by=self.admin,
            status=Invitation.Status.REVOKED,
            expires_at=timezone.now() + timezone.timedelta(days=7),
        )
        self.assertFalse(inv.is_valid)


class PlatformAccessModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user("member", email="m@co.com", password="pw")
        self.company = Company.objects.create(name="Acme")
        self.membership = Membership.objects.create(
            user=self.user, company=self.company, role=Membership.Role.MEMBER
        )
        self.integration = CompanyIntegration.objects.create(
            company=self.company, service="microsoft", status="active"
        )

    def test_create_platform_access(self):
        pa = PlatformAccess.objects.create(
            membership=self.membership,
            integration=self.integration,
            permission=PlatformAccess.Permission.VIEW,
        )
        self.assertEqual(pa.permission, "view")

    def test_unique_membership_integration(self):
        PlatformAccess.objects.create(
            membership=self.membership,
            integration=self.integration,
            permission=PlatformAccess.Permission.VIEW,
        )
        with self.assertRaises(Exception):
            PlatformAccess.objects.create(
                membership=self.membership,
                integration=self.integration,
                permission=PlatformAccess.Permission.MANAGE,
            )


class InviteFlowTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_user(
            "admin", email="admin@co.com", password="StrongPass123!"
        )
        self.company = Company.objects.create(name="Acme")
        Membership.objects.create(user=self.admin, company=self.company, role=Membership.Role.OWNER)
        self.client.login(username="admin", password="StrongPass123!")

    def test_admin_can_send_invite(self):
        resp = self.client.post(reverse("companies:invite"), {
            "email": "newguy@co.com",
            "role": "member",
        })
        self.assertEqual(resp.status_code, 302)
        self.assertTrue(Invitation.objects.filter(email="newguy@co.com").exists())

    def test_member_cannot_send_invite(self):
        member = User.objects.create_user("mem", email="mem@co.com", password="StrongPass123!")
        Membership.objects.create(user=member, company=self.company, role=Membership.Role.MEMBER)
        self.client.login(username="mem", password="StrongPass123!")
        resp = self.client.post(reverse("companies:invite"), {
            "email": "sneaky@co.com",
            "role": "member",
        })
        self.assertEqual(resp.status_code, 302)
        self.assertFalse(Invitation.objects.filter(email="sneaky@co.com").exists())

    def test_accept_invite_creates_membership(self):
        inv = Invitation.objects.create(
            company=self.company,
            email="joiner@co.com",
            role=Membership.Role.MEMBER,
            invited_by=self.admin,
            expires_at=timezone.now() + timezone.timedelta(days=7),
        )
        self.client.logout()
        resp = self.client.post(reverse("companies:accept_invite", args=[inv.token]), {
            "username": "joiner",
            "password": "StrongJoinPass1!",
            "first_name": "Joe",
            "last_name": "Iner",
        })
        self.assertEqual(resp.status_code, 302)
        inv.refresh_from_db()
        self.assertEqual(inv.status, Invitation.Status.ACCEPTED)
        self.assertTrue(
            Membership.objects.filter(user__username="joiner", company=self.company).exists()
        )

    def test_expired_invite_shows_invalid(self):
        inv = Invitation.objects.create(
            company=self.company,
            email="late@co.com",
            invited_by=self.admin,
            expires_at=timezone.now() - timezone.timedelta(hours=1),
        )
        self.client.logout()
        resp = self.client.get(reverse("companies:accept_invite", args=[inv.token]))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "expired")

    def test_revoke_invite(self):
        inv = Invitation.objects.create(
            company=self.company,
            email="gone@co.com",
            invited_by=self.admin,
            expires_at=timezone.now() + timezone.timedelta(days=7),
        )
        resp = self.client.post(reverse("companies:revoke_invite", args=[inv.token]))
        self.assertEqual(resp.status_code, 302)
        inv.refresh_from_db()
        self.assertEqual(inv.status, Invitation.Status.REVOKED)


class AccessControlTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_user(
            "admin", email="admin@co.com", password="StrongPass123!"
        )
        self.member = User.objects.create_user(
            "member", email="member@co.com", password="StrongPass123!"
        )
        self.company = Company.objects.create(name="Acme")
        self.admin_membership = Membership.objects.create(
            user=self.admin, company=self.company, role=Membership.Role.OWNER
        )
        self.member_membership = Membership.objects.create(
            user=self.member, company=self.company, role=Membership.Role.MEMBER
        )
        self.ms_integration = CompanyIntegration.objects.create(
            company=self.company, service="microsoft", status="active"
        )

    def test_admin_can_manage_access(self):
        self.client.login(username="admin", password="StrongPass123!")
        resp = self.client.post(
            reverse("companies:manage_access", args=[self.member_membership.id]),
            {f"perm_{self.ms_integration.id}": "view"},
        )
        self.assertEqual(resp.status_code, 302)
        self.assertTrue(
            PlatformAccess.objects.filter(
                membership=self.member_membership,
                integration=self.ms_integration,
                permission="view",
            ).exists()
        )

    def test_member_cannot_manage_access(self):
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.post(
            reverse("companies:manage_access", args=[self.member_membership.id]),
            {f"perm_{self.ms_integration.id}": "manage"},
        )
        # Redirected to dashboard, no access created
        self.assertEqual(resp.status_code, 302)
        self.assertFalse(PlatformAccess.objects.filter(membership=self.member_membership).exists())

    def test_admin_can_remove_member(self):
        self.client.login(username="admin", password="StrongPass123!")
        resp = self.client.post(
            reverse("companies:remove_member", args=[self.member_membership.id])
        )
        self.assertEqual(resp.status_code, 302)
        self.member_membership.refresh_from_db()
        self.assertFalse(self.member_membership.is_active)

    def test_cannot_remove_owner(self):
        self.client.login(username="admin", password="StrongPass123!")
        resp = self.client.post(
            reverse("companies:remove_member", args=[self.admin_membership.id])
        )
        self.assertEqual(resp.status_code, 302)
        self.admin_membership.refresh_from_db()
        self.assertTrue(self.admin_membership.is_active)


class PlatformAccessDecoratorTests(TestCase):
    """Test that platform views enforce access control for members."""

    def setUp(self):
        self.admin = User.objects.create_user(
            "admin", email="admin@co.com", password="StrongPass123!"
        )
        self.member = User.objects.create_user(
            "member", email="member@co.com", password="StrongPass123!"
        )
        self.company = Company.objects.create(name="Acme")
        self.admin_membership = Membership.objects.create(
            user=self.admin, company=self.company, role=Membership.Role.OWNER
        )
        self.member_membership = Membership.objects.create(
            user=self.member, company=self.company, role=Membership.Role.MEMBER
        )
        self.ms_integration = CompanyIntegration.objects.create(
            company=self.company, service="microsoft", status="active"
        )

    def test_admin_always_has_access(self):
        """Admins bypass PlatformAccess — they always have full access."""
        self.client.login(username="admin", password="StrongPass123!")
        # Email inbox requires microsoft view access
        resp = self.client.get(reverse("email_hub:inbox"))
        # Should get 200 (or any non-redirect), not blocked
        self.assertNotEqual(resp.status_code, 302)

    def test_member_without_access_is_blocked(self):
        """Member with no PlatformAccess is redirected."""
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.get(reverse("email_hub:inbox"))
        self.assertEqual(resp.status_code, 302)

    def test_member_with_view_access_can_view(self):
        """Member with view access can access inbox."""
        PlatformAccess.objects.create(
            membership=self.member_membership,
            integration=self.ms_integration,
            permission=PlatformAccess.Permission.VIEW,
        )
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.get(reverse("email_hub:inbox"))
        # Should not be blocked (302 to dashboard)
        # May still redirect to connect if no token, but not to dashboard
        if resp.status_code == 302:
            self.assertNotIn("dashboard", resp.url)

    def test_member_view_access_cannot_compose(self):
        """Member with view-only access is blocked from compose (needs reply)."""
        PlatformAccess.objects.create(
            membership=self.member_membership,
            integration=self.ms_integration,
            permission=PlatformAccess.Permission.VIEW,
        )
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.get(reverse("email_hub:compose"))
        self.assertEqual(resp.status_code, 302)

    def test_member_reply_access_can_compose(self):
        """Member with reply access can access compose."""
        PlatformAccess.objects.create(
            membership=self.member_membership,
            integration=self.ms_integration,
            permission=PlatformAccess.Permission.REPLY,
        )
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.get(reverse("email_hub:compose"))
        if resp.status_code == 302:
            self.assertNotIn("dashboard", resp.url)


# ── Phase 4 Tests ─────────────────────────────────────────────────────────────


class ActivityLogModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user("alice", password="pw")
        self.company = Company.objects.create(name="Acme")
        Membership.objects.create(user=self.user, company=self.company, role=Membership.Role.OWNER)

    def test_create_activity_log(self):
        log = ActivityLog.objects.create(
            company=self.company,
            user=self.user,
            action="email_sent",
            platform="microsoft",
            detail="To: bob@co.com",
        )
        self.assertEqual(log.company, self.company)
        self.assertEqual(log.action, "email_sent")
        self.assertEqual(log.get_action_display(), "Sent email")

    def test_ordering_is_newest_first(self):
        import time
        ActivityLog.objects.create(company=self.company, user=self.user, action="login")
        time.sleep(0.01)
        ActivityLog.objects.create(company=self.company, user=self.user, action="email_sent")
        logs = list(ActivityLog.objects.filter(company=self.company))
        # newest first
        self.assertEqual(logs[0].action, "email_sent")


class ActivityLogViewTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_user("admin", email="admin@co.com", password="StrongPass123!")
        self.member = User.objects.create_user("member", email="member@co.com", password="StrongPass123!")
        self.company = Company.objects.create(name="Acme")
        Membership.objects.create(user=self.admin, company=self.company, role=Membership.Role.OWNER)
        Membership.objects.create(user=self.member, company=self.company, role=Membership.Role.MEMBER)
        ActivityLog.objects.create(company=self.company, user=self.admin, action="login")
        ActivityLog.objects.create(company=self.company, user=self.member, action="email_viewed", platform="microsoft")

    def test_admin_can_view_activity_log(self):
        self.client.login(username="admin", password="StrongPass123!")
        resp = self.client.get(reverse("companies:activity_log"))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Activity Log")

    def test_member_cannot_view_activity_log(self):
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.get(reverse("companies:activity_log"))
        self.assertEqual(resp.status_code, 302)

    def test_filter_by_platform(self):
        self.client.login(username="admin", password="StrongPass123!")
        resp = self.client.get(reverse("companies:activity_log") + "?platform=microsoft")
        self.assertEqual(resp.status_code, 200)
        # Should contain the microsoft log but context should have filtered logs
        self.assertEqual(len(resp.context["logs"]), 1)

    def test_filter_by_action(self):
        self.client.login(username="admin", password="StrongPass123!")
        resp = self.client.get(reverse("companies:activity_log") + "?action=login")
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.context["logs"]), 1)


class LogActivityHelperTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_user("admin", email="admin@co.com", password="StrongPass123!")
        self.company = Company.objects.create(name="Acme")
        Membership.objects.create(user=self.admin, company=self.company, role=Membership.Role.OWNER)

    def test_log_activity_creates_record(self):
        """Test that log_activity creates an ActivityLog via an actual view action."""
        self.client.login(username="admin", password="StrongPass123!")
        # Invite a member — this should create an activity log entry
        self.client.post(reverse("companies:invite"), {"email": "test@co.com", "role": "member"})
        log = ActivityLog.objects.filter(company=self.company, action="invite_sent").first()
        self.assertIsNotNone(log)
        self.assertIn("test@co.com", log.detail)


class SidebarAccessTests(TestCase):
    """Test sidebar shows/hides links based on platform access."""

    def setUp(self):
        self.member = User.objects.create_user("member", email="member@co.com", password="StrongPass123!")
        self.company = Company.objects.create(name="Acme")
        self.membership = Membership.objects.create(
            user=self.member, company=self.company, role=Membership.Role.MEMBER
        )

    def test_sidebar_hides_email_without_ms_access(self):
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.get(reverse("dashboard:home"))
        # The sidebar nav should not contain the Email link
        content = resp.content.decode()
        # Sidebar is inside <nav id="sidebar">, email link text is "Email"
        # Without ms access, {% if has_ms_access %} block should be skipped
        self.assertNotIn('<i class="bi bi-envelope me-2"></i>Email', content)

    def test_sidebar_hides_slack_without_slack_access(self):
        self.client.login(username="member", password="StrongPass123!")
        resp = self.client.get(reverse("dashboard:home"))
        self.assertNotIn('<i class="bi bi-slack me-2"></i>Slack', resp.content.decode())

