# Generated by Django 5.2.14 on 2026-05-28 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendly_event_uri', models.CharField(blank=True, db_index=True, help_text='Calendly event resource URI', max_length=500)),
                ('event_type_name', models.CharField(blank=True, help_text="e.g. '30 Minute Meeting'", max_length=255)),
                ('event_type_uri', models.CharField(blank=True, help_text='Calendly event type resource URI', max_length=500)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scheduling_link', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('invitee_name', models.CharField(blank=True, max_length=255)),
                ('invitee_email', models.EmailField(blank=True, max_length=254)),
                ('created_via', models.CharField(choices=[('slack_bot', 'Slack Bot'), ('web_ui', 'Web UI'), ('webhook', 'Webhook')], default='slack_bot', max_length=20)),
                ('slack_channel_id', models.CharField(blank=True, help_text='Slack channel where the meeting was requested', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='companies.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
