# Generated by Django 5.2.14 on 2026-05-29 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp Business'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('access_token_enc', models.BinaryField(blank=True, null=True)),
                ('refresh_token_enc', models.BinaryField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, help_text='Facebook/Instagram Page ID', max_length=255)),
                ('phone_number_id', models.CharField(blank=True, help_text='WhatsApp Business Phone Number ID', max_length=100)),
                ('waba_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=100)),
                ('telegram_bot_username', models.CharField(blank=True, help_text='Telegram Bot @username', max_length=100)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Default Telegram Chat/Group ID', max_length=100)),
                ('api_key_enc', models.BinaryField(blank=True, help_text='Encrypted API Key / App Secret', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook verification token', max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='Platform webhook callback URL', max_length=500)),
                ('can_read_messages', models.BooleanField(default=True, help_text='Permission to read incoming messages')),
                ('can_send_messages', models.BooleanField(default=False, help_text='Permission to send/reply to messages')),
                ('can_auto_reply', models.BooleanField(default=False, help_text='Permission for AI bot auto-reply')),
                ('can_post_content', models.BooleanField(default=False, help_text='Permission to publish posts')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='companies.company')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
                'unique_together': {('company', 'platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp Business'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('auto_send', models.BooleanField(default=False, help_text='Send reply without human confirmation')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords that trigger auto-reply. Empty = reply to all.')),
                ('reply_to_dms', models.BooleanField(default=True, help_text='Auto-reply to direct messages')),
                ('reply_to_comments', models.BooleanField(default=False, help_text='Auto-reply to post comments')),
                ('reply_to_groups', models.BooleanField(default=False, help_text='Auto-reply in group chats')),
                ('custom_instructions', models.TextField(blank=True, help_text='Custom instructions for the AI bot (tone, style, what to include/exclude).')),
                ('persona_name', models.CharField(blank=True, help_text="Bot persona name (e.g., 'Business Assistant')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auto_rules', to='companies.company')),
                ('account', models.ForeignKey(blank=True, help_text='Leave blank to apply to all accounts of this platform.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_rules', to='social_media.socialmediaaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, max_length=255)),
                ('recipient_id', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('message_type', models.CharField(default='text', help_text='text, image, video, document, etc.', max_length=50)),
                ('platform_message_id', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_media.socialmediaaccount')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BotConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('classified', 'Message Classified'), ('auto_replied', 'Auto Reply Sent'), ('read', 'Message Read'), ('escalated', 'Escalated to Human'), ('ignored', 'Ignored (no rule match)')], max_length=20)),
                ('ai_classification', models.CharField(blank=True, max_length=50)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_reply_text', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI confidence score 0-1', null=True)),
                ('was_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to='social_media.socialmediaaccount')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_logs', to='social_media.socialmediamessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Post content / message text')),
                ('media_url', models.URLField(blank=True, help_text='Attached image/video URL', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, help_text='ID returned by platform after publishing', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_media.socialmediaaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
