# Generated by Django 5.2.14 on 2026-05-21 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_invitation_platformaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Logged in'), ('invite_sent', 'Sent invitation'), ('invite_accepted', 'Accepted invitation'), ('member_removed', 'Removed member'), ('access_updated', 'Updated platform access'), ('integration_connected', 'Connected integration'), ('integration_disconnected', 'Disconnected integration'), ('email_viewed', 'Viewed email'), ('email_sent', 'Sent email'), ('meetings_viewed', 'Viewed meetings'), ('slack_channel_viewed', 'Viewed Slack channel'), ('slack_message_sent', 'Sent Slack message'), ('slack_auto_reply', 'Slack auto-reply sent'), ('ai_summarize', 'AI summarization'), ('ai_reply', 'AI reply generated')], max_length=40)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='companies_a_company_c08112_idx'), models.Index(fields=['user', '-created_at'], name='companies_a_user_id_732b24_idx'), models.Index(fields=['action'], name='companies_a_action_cba88a_idx')],
            },
        ),
    ]
