# Generated by Django 5.2.14 on 2026-05-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Logged in'), ('invite_sent', 'Sent invitation'), ('invite_accepted', 'Accepted invitation'), ('member_removed', 'Removed member'), ('access_updated', 'Updated platform access'), ('integration_connected', 'Connected integration'), ('integration_disconnected', 'Disconnected integration'), ('email_viewed', 'Viewed email'), ('email_sent', 'Sent email'), ('meetings_viewed', 'Viewed meetings'), ('slack_channel_viewed', 'Viewed Slack channel'), ('slack_message_sent', 'Sent Slack message'), ('slack_auto_reply', 'Slack auto-reply sent'), ('presence_viewed', 'Viewed presence'), ('chat_viewed', 'Viewed Teams chat'), ('chat_message_sent', 'Sent Teams message'), ('channel_message_sent', 'Sent channel message'), ('onedrive_browsed', 'Browsed OneDrive'), ('onedrive_uploaded', 'Uploaded to OneDrive'), ('onedrive_downloaded', 'Downloaded from OneDrive'), ('onedrive_deleted', 'Deleted OneDrive item'), ('onedrive_shared', 'Shared OneDrive item'), ('todo_viewed', 'Viewed To Do'), ('todo_created', 'Created task'), ('todo_updated', 'Updated task'), ('todo_deleted', 'Deleted task'), ('planner_viewed', 'Viewed Planner'), ('contacts_viewed', 'Viewed contacts'), ('ai_summarize', 'AI summarization'), ('ai_reply', 'AI reply generated')], max_length=40),
        ),
    ]
