# Generated by Django 5.2.14 on 2026-05-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_companyintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='jira_account_id',
            field=models.CharField(blank=True, help_text='Atlassian accountId from /rest/api/3/myself', max_length=128),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='jira_avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='jira_display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
