# Generated by Django 5.2.14 on 2026-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_jira_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintegration',
            name='jira_webhook_id',
            field=models.CharField(blank=True, help_text='Jira webhook ID for deletion', max_length=100),
        ),
        migrations.AddField(
            model_name='companyintegration',
            name='jira_webhook_secret',
            field=models.CharField(blank=True, help_text='Shared secret for webhook validation', max_length=64),
        ),
    ]
