# Generated by Django 5.2.14 on 2026-05-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('lead_display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_projects', to='companies.company')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('company', 'project_id')},
            },
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=50)),
                ('issue_key', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('issue_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('status_category', models.CharField(choices=[('new', 'New'), ('indeterminate', 'In Progress'), ('done', 'Done'), ('undefined', 'Undefined')], default='undefined', max_length=20)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('assignee_display_name', models.CharField(blank=True, max_length=255)),
                ('reporter_display_name', models.CharField(blank=True, max_length=255)),
                ('created_at_jira', models.DateTimeField(blank=True, null=True)),
                ('updated_at_jira', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='jira_hub.jiraproject')),
            ],
            options={
                'ordering': ['-updated_at_jira'],
            },
        ),
        migrations.CreateModel(
            name='JiraSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('projects_synced', models.IntegerField(default=0)),
                ('issues_synced', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_sync_logs', to='companies.company')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JiraComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50)),
                ('author_display_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at_jira', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jira_hub.jiraissue')),
            ],
            options={
                'ordering': ['created_at_jira'],
                'unique_together': {('issue', 'comment_id')},
            },
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['company', 'status_category'], name='jira_hub_ji_company_6fafdb_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['company', 'issue_key'], name='jira_hub_ji_company_06e32b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jiraissue',
            unique_together={('company', 'issue_id')},
        ),
    ]
